name: Update Lines of Code Badge

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight UTC
  workflow_dispatch: # Allows manual triggering

jobs:
  update-loc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install tokei
        run: cargo install tokei

      - name: Count lines of code
        id: loc
        run: |
          tokei --output json > loc.json
          TOTAL_LINES=$(jq '.total.code' loc.json)
          echo "TOTAL_LINES=$TOTAL_LINES" >> $GITHUB_ENV

      - name: Generate badge
        run: |
          BADGE_URL="https://img.shields.io/badge/Lines%20of%20Code-${{ env.TOTAL_LINES }}-58A6FF"
          echo "BADGE_URL=$BADGE_URL" >> $GITHUB_ENV

      - name: Update README
        run: |
          sed -i "s|https://img.shields.io/badge/From%20Hello%20World%20I%27ve%20Written-[0-9.]*%20million%20lines%20of%20code-blue|${{ env.BADGE_URL }}|" README.md
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add README.md
          git commit -m "Update lines of code badge" || echo "No changes to commit"
          git push
